### ISSUE TITLE
How to include other packages?

### ISSUE THREAD

**Issue by begriffs** [lyokha/nginx-haskell-module#1]
I notice the README example imports `Text.Regex.PCRE` which means the `regex-pcre` package is available. If I wanted to use another library such as `aeson` how would I make it available for my nginx haskell code?

**Comment by lyokha** [comment]
What you put in directives ``haskell compile`` and ``haskell load`` is a normal haskell *main*-less program except it cannot use symbols ``'`` as they would break the directive's boundaries (if you used them to wrap the code argument like in the example, but see below the function ``urlDecode``). So you can just put imports with required libraries in it. If you have to fine-tune package settings while ghc compiles it (paths, pragmas etc.) you can use directive ``haskell ghc_extra_flags`` like in the example.

I made a small check of ``Data.Aeson``. Add in the example following imports:

```haskell
import           Data.Aeson
import qualified Data.ByteString.Lazy.Char8 as B
import           Data.Maybe
```

and simple decodable check function

```haskell
isDecodable x = isJust
    (decode $ B.pack $ fromMaybe "" $ urlDecode x :: Maybe [Int])
NGX_EXPORT_B_S (isDecodable)
```

``isDecodable`` requires ``urlDecode`` that I took from [here](http://www.rosettacode.org/wiki/URL_decoding#Haskell) but replaced characters with ``'`` by view patterns with ``C.ord`` (pragma ``ViewPatterns`` is included in the code wrapper from the module):

```haskell
urlDecode :: String -> Maybe String
urlDecode [] = Just []
urlDecode ((C.ord -> 37) : xs) =
  case xs of
    (a:b:xss) ->
      urlDecode xss
      >>= return . ((C.chr . read $ "0x" ++ [a,b]) :)
    _ -> Nothing
urlDecode ((C.ord -> 43) : xs) = urlDecode xs >>= return . (C.chr 32 :)
urlDecode (x:xs) = urlDecode xs >>= return . (x :)
```

Now you can add into ``locaton /`` a new if (with, say, ``$arg_m``):

```nginx
            if ($arg_m) {
                haskell_run isDecodable $hs_a $arg_m;
                echo "isDecodable ($arg_m) = $hs_a";
                break;
            }

```

, start nginx and check ``isDecodable`` with curl:

```
$ curl 'http://localhost:8010/?m=%5B1%2C2%2C3%5D'    # URL-encoded [1,2,3]
isDecodable (%5B1%2C2%2C3%5D) = 1
curl 'http://localhost:8010/?m=hahajaghsg'
isDecodable (hahajaghsg) = 0
```

This example requires conversions from ByteString to String, probably I must add support for ByteStrings in the module for dealing with long texts.

**Comment by begriffs** [comment]
Thank you for your research and detailed answer.

**Comment by lyokha** [comment]
please see new examples in the README, also support for functions with ByteString argument / return value was added
